######################################################################
# Automatically generated by qmake (2.01a) on 20. jun 01:22:25 2007
######################################################################

TEMPLATE = app
TARGET =
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += turing.h
SOURCES += main.cpp \
           turing.cpp

CONFIG += console
